version: '3.7'

x-anchors:
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
  args: &current-user-info
    user: ${USER:-user1}
    user_id: ${USER_ID:-1000}
    group_id: ${GROUP_ID:-1000}

services:
  chat:
    build:
      context: ./app
      dockerfile: Dockerfile
      args: *current-user-info
    volumes:
      - ./app:/usr/src/env/app
    dns: 8.8.8.8
    ports:
      - "8000:8000"
    environment: *env

  nginx:
    image: nginx:1.18-alpine
    depends_on:
     - chat
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  coturn:
    build:
      context: ./coturn
      dockerfile: Dockerfile
    ports:
      - "3478:3478"
      - "3479:3479"
      - "5349:5349"
      - "5350:5350"
    volumes:
      - ./coturn/turnserver-alt.conf:/etc/turnserver.conf
      - ./certbot/conf:/etc/letsencrypt

